name: Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Card 1 - Stats
        uses: lowlighter/metrics@latest
        with:
          user: Chagas09
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: assets/github-stats.svg

          template: classic
          base: header, activity, community, repositories
          config_timezone: America/Sao_Paulo

      - name: Card 2 - Languages
        uses: lowlighter/metrics@latest
        with:
          user: Chagas09
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: assets/top-langs.svg

          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          config_timezone: America/Sao_Paulo
